spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: 123456
    drver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8181